name = "hello-world-web"
compatibility_date = "2025-09-01"
pages_build_output_dir = "dist"

# Production environment variables
[vars]
VITE_API_URL = "https://hello-world.mvpkit.dev"
VITE_PROJECT_NAME = "hello-world"
VITE_DOMAIN = "hello-world.mvpkit.dev"
VITE_NODE_ENV = "production"
VITE_FRONTEND_PORT = "3000"
VITE_ALLOWED_HOSTS = "hello-world.mvpkit.dev,*.hello-world.mvpkit.dev"