name = "hello-world-api"
main = "src/index.ts"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

# Default resources (development/local)
[[d1_databases]]
binding = "DB"
database_name = "hello-world-db-dev"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "0000000000000000000000000000000000"

[[r2_buckets]]
binding = "R2"
bucket_name = "hello-world-bucket-dev"

# Local development server configuration
[dev]
port = 8787
local_protocol = "http"
upstream_protocol = "http"


# Production environment (used for deployment)
[env.production]
name = "hello-world-api"

[env.production.vars]
NODE_ENV = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "hello-world-db"
database_id = "5d0f12a0-75e4-4499-add7-b18436cb8834"
migrations_dir = "drizzle"

[[env.production.kv_namespaces]]
binding = "KV"
id = "04cba09893334fd48e8edc2414a01275"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "hello-world-bucket"