name = "hello-world-app"
pages_build_output_dir = "./dist"
compatibility_date = "2025-09-01"

[vars]
VITE_PROJECT_NAME = "hello-world-app"
VITE_DOMAIN = "app.hello-world.mvpkit.dev"
VITE_NODE_ENV = "production"
VITE_FRONTEND_PORT = "3002"
VITE_ALLOWED_HOSTS = "app.hello-world.mvpkit.dev,hello-world.mvpkit.dev,*.hello-world.mvpkit.dev"
